### PR TITLE
research_consent should be true not "YES"

### PR DESCRIPTION
**Pull request by DevChima**

### CODE REVIEW

**Comment by bearnard** [comment]
there seem to be other places that look for a string eg: https://github.com/praekeltfoundation/ndoh-jsbox/blob/develop/src/ussd_tb_check.js#L274

Since the django app accepts boolean values you need to be sure jsbox sends `false` when they refuse consent

**Comment by DevChima** [comment]
@bearnard If they reply "No" they exit the app and we don't do a SEND. https://github.com/praekeltfoundation/ndoh-jsbox/blob/1d2df8c19e6012c00bda244f101af6cf1fdf0274/src/ussd_tb_check.js#L295

**Comment by bearnard** [comment]
ah, cool, does `ChoiceState` not handle this for us?

**Comment by bearnard** [comment]
👍 otherwise

**Pull request merged**
