### PR TITLE
MomConnect servicerating migration

### PR DESCRIPTION
**Pull request by NicolaasDieBaas**

### CODE REVIEW

**Comment by NicolaasDieBaas** [comment]
Travis checks failing because new seed-jsbox-utils changes need landing...

package.json --> seed-jsbox-utils will need to be bumped to 0.1.9 after changes have been landed

**Comment by NicolaasDieBaas** [comment]
@gsvr @imsickofmaps please review.

**Comment by gsvr** [comment]
@NicolaasDieBaas Please review my changes and update seed-jsbox-utils version.

**Comment by NicolaasDieBaas** [comment]
@gsvr 👍  remember to rename `get_servicerating_status` function to `list_serviceratings`

**Comment by gsvr** [comment]
:+1: @NicolaasDieBaas Please land it

**Pull request merged**
