### PR TITLE
Prevent duplicate clinic registrations

### PR DESCRIPTION
**Pull request by alexmuller**
This is a first iteration of what a solution to duplicate clinic registrations might look like.

There may be some edge cases that I haven't considered.

If this looks ok I'll add some tests for it before merging.

### CODE REVIEW

**Comment by rudigiesler** [comment]
Maybe we should be offering a choice to type in a different number, rather than just ending the registration?

Otherwise looks good to me

**Comment by alexmuller** [comment]
@rudigiesler Thanks, have done! I've got most of the tests working but there are now just a couple I can't figure out. I'm not sure why fixture 54 (messagesets) is now being used.

**Comment by alexmuller** [comment]
All sorted now with help from Rudi! Before deployment this will need a token added to the config repo.

**Comment by alexmuller** [comment]
Oh also what's the situation with localisation in this repo? Do we need translations for this text?

**Comment by rudigiesler** [comment]
@alexmuller Yes we do need translations. You will find them in the `config` folder. They usually generate large diffs, so we usually do them in a separate PR.

**Comment by alexmuller** [comment]
Updated to fix @KaitCrawford's feedback that we also need to do this check at `state_mobile_no`. Finding this repo really hard to make changes to 😞 

Also need to do translations of the new text.

**Review by KaitCrawford — APPROVED** [review]
:+1:

**Pull request merged**
