### PR TITLE
Allow skipping of white list for pilot

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
https://github.com/praekeltfoundation/ndoh-dockerconfig/pull/70 has the config change.

**Comment by smn** [comment]
Ready for review @rudigiesler @KaitCrawford @erikh360

**Comment by smn** [comment]
I've left the whitelist (sorry terrible name) checks in there for possible future use should we need to still use this.

**Review by KaitCrawford — APPROVED** [review]
:+1:

**Pull request merged**
